#!/usr/bin/env python
import argparse
import json
import os
import sys

import main_mnist


args = main_mnist.parse_args()
with open("/opt/ml/input/config/hyperparameters.json") as f:
    params = json.load(f)
    args.epochs = int(params["epochs"])
    args.save_model = bool(params["save_model"])
    args.output_dir = "/opt/ml/model"

print(args)
main_mnist.main(args)
sys.exit(0)
